import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Navid Salehi-Memory Card Flip Game",
  description: "Generated by Navid for Challenge ",
  icons: {icon:"/images/favicon.png"}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
