import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";

export const metadata: Metadata = {
  title: "Navid Salehi-Memory Card Flip Game",
  description: "Generated by Navid for Challenge ",
  icons: { icon: "/images/favicon.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
